live_config_reload = true
# "window.dynamic_title" = true
# "window.opacity" = 0.87

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "L"
mods = "Alt|Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.hints]
# modifiers = "Shift|Alt"

[scrolling]
history = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.8

[window.dimensions]
columns = 180
lines = 50

[window.padding]
x = 1
y = 0
